name: Web App

on:
  push:
    branches:
      - main
  schedule:
    # <minute [0,59]> <hour [0,23]> <day of the month [1,31]> <month of the year [1,12]> <day of the week [0,6]>
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    # Run every Monday at 23:26:00 UTC (Monday at 15:26:00 PST)
    # We offset from the hour and half hour to go easy on the servers :)
    - cron: '26 23 * * 1'

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    # Build Web
    - name: Install Web App Dependencies
      run: |
        cd web/
        npm i
    - name: Build Web App
      run: |
        cd web/
        npm run build

    # Deploy Web
    - name: Publish Docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: web/build/