version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "cdp-backend"
    commit-message:
      prefix: "ci(dependabot):"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@councildataproject/cdp-frontend"
    commit-message:
      prefix: "ci(dependabot):"
